# way 1
node {
    stage 'cloning repo'
    git 'https://github.com/g0t4/jenkins2-course-spring-boot.git'
    
    def project_path = "spring-boot-samples/spring-boot-sample-atmosphere/"
    dir(project_path) {
        
        stage 'cleaning and packaging'
        sh 'mvn clean package'
       
       stage 'archiving artifacts'
       archiveArtifacts 'target/*.jar'

    }
}

# ================================================================================ #

# way 2 
node {
    
    stage('cloning repo') {
        git 'https://github.com/g0t4/jenkins2-course-spring-boot.git'
    }

    def project_path = "spring-boot-samples/spring-boot-sample-atmosphere/"
    dir(project_path) {

        stage('cleaning and packaging') {
            sh 'mvn clean package'
        }

        stage('archiving artifacts') {
            archiveArtifacts 'target/*.jar'
        }
    }

}

# =============================================================================== #
# Ref: https://github.com/g0t4/jenkins2-course-spring-boot 
